/**
 * @id PP-CORE-MCK-007 (POO-1598 S5)
 * @name Paybis captured purchase (mock, wire-level ground truth)
 * @implements-rules-version v1 (POO-1598 rules v1)
 *
 * The first real production Paybis capture (2026-08-17, EUR
 * buyer, card, captured by the S1-S4 instrumentation this same epic built on `pool-party-api`),
 * committed as a replayable fixture set. POO-1598's whole premise: every unknown that has blocked this
 * epic is a vendor behaviour nobody had observed, and a log a human has to transcribe is not a
 * deliverable, a fixture is. This module and its `paybisCapture/*.capture.json` siblings are that
 * fixture set, at the PAYBIS WIRE level: exactly what `pool-party-api`'s `TracedHttpService` recorded
 * on the outbound hop to `widget-api.paybis.com`, not pool-party-api's own (further-wrapped) DTO back
 * to this app. `paybisCapture.test.ts` proves the two are close enough to matter: every captured
 * payment-methods list parses through this app's real {@link onRampPaymentMethodsResponseSchema} and
 * every captured quote parses through the real {@link onRampQuoteResponseSchema}, both imported from
 * `@/lib/onramp/schemas` verbatim, not a copy. That is the strongest compatibility evidence available
 * without pool-party-api's own source in this repo.
 *
 * ## What is REAL and what is SYNTHETIC (`CR-CORE-027`)
 *
 * The capture arrived already boundary-redacted (`[redacted:user-ip]`, `[redacted:email]`,
 * `[redacted:partner-user-id]`, `[redacted:wallet-address]`), which this module leaves untouched: a
 * v3/request replay does not need those fields to look real, only to be present. On top of that
 * boundary redaction, `CR-CORE-027` requires the following to become SYNTHETIC before a capture is
 * committed, and this module does exactly that and nothing more:
 *
 *   - **Every `quoteId` and the one `requestId`** from the source capture
 *     are replaced with `mock-poo1598-*` tokens, chosen to self-label as mock per the
 *     `mock-service-blueprint` identifier rule. The replacement preserves every JOIN in the capture: the
 *     422 request still carries the synthetic id of the quote that produced it
 *     ({@link MOCK_PAYBIS_CAPTURE_QUOTE_10USDC_CARD_B}'s `id`), and the 201 request still carries the
 *     synthetic id of ITS quote ({@link MOCK_PAYBIS_CAPTURE_QUOTE_11USDC_CARD_B}'s `id`). A future mock
 *     service can replay quote-then-request exactly as the real buyer did.
 *   - **The masked wallet.** The source's `[redacted:wallet-address]` boundary placeholder is replaced
 *     with one deterministic, valid-format, self-evidently-mock address
 *     ({@link MOCK_PAYBIS_CAPTURE_WALLET}), generated by the same seeded-hash approach as
 *     `src/mocks/data/pools.ts`'s `mockAddress`, not a real address with characters changed.
 *   - **`requestId`, `country`/`countryCode`.** This specific capture never sent a `country`/
 *     `countryCode` field at all (checked directly against the source text), so there is nothing to
 *     synthesize there; recorded here so a reader does not go looking for a redaction that never
 *     applied.
 *
 * Every other figure, every fee, every minimum, every timestamp and every payment-method id
 * (`pool-party-credit-card`, `pool-party_bridgerpay_revolutpay`, …) is REAL, copied byte-for-byte from
 * the capture. This is the deliberate exception the identifiers make room for: realism applies to the
 * *observable values*, not to the correlators, so a real-mode integration bug is never confused with a
 * gap between an idealized mock and this fixture.
 *
 * ## One field the redaction ITSELF corrupted (`POO-1668`)
 *
 * `exchangeRate.rate` reads `"1.[redacted:card-number]"` on 4 of the 13 quote records
 * ({@link MOCK_PAYBIS_CAPTURE_QUOTE_100USDC}, {@link MOCK_PAYBIS_CAPTURE_QUOTE_9USDC},
 * {@link MOCK_PAYBIS_CAPTURE_QUOTE_5USDC}, {@link MOCK_PAYBIS_CAPTURE_QUOTE_255USDC}): the PAN scanner
 * matched a 16-digit Luhn-valid run that happens to start right after the decimal point. Copying that
 * string into a fixture would ship a value that was never a rate at all. The true instantaneous rate for
 * those four exact requests cannot be recovered, so this module does NOT fabricate one; instead it
 * substitutes the nearest-in-time INTACT rate this same capture actually observed,
 * `"1.1572441341898636"` (seen at 15:52:54 and 15:53:40, bracketing all four corrupted requests, which
 * span 15:51:07-15:53:03). The substitution is corroborated, not guessed: each corrupted record's sibling
 * `exchangeRateCryptoToFiat.rate` field survived redaction intact at `"0.86422203"` for all four, and
 * `1 / 0.86422203 ≈ 1.15708`, in the same neighbourhood as the substituted value. The other 9 quote
 * records carry their own genuinely intact, genuinely DIFFERENT rates
 * (`"1.1573782452263905"`, `"1.1575123873503157"`), left exactly as captured: this fixture does not
 * normalize a real, moving exchange rate into one number.
 *
 * ## The cases this capture exists to preserve
 *
 * 1. **A method priced AND refused in the same response** ({@link MOCK_PAYBIS_CAPTURE_QUOTE_10USDC_CARD_B},
 *    POO-1666's root cause): `pool-party-credit-card` appears in `paymentMethods` at EUR 10.53 AND in
 *    `paymentMethodErrors` ("at least 10.003001 USDC"). Its controlled twin at 11 USDC
 *    ({@link MOCK_PAYBIS_CAPTURE_QUOTE_11USDC_CARD_B}) carries NO `paymentMethodErrors` and is the exact
 *    quote the capture's 201 mint used. Both are kept, unmodified, on purpose.
 * 2. **SEPA is non-instant, by omission.** `pool-party-manual-bank-transfer` carries
 *    `labels: ["low-fee"]` only, never `"instant"`, and `minAmount.amount === "200.00"` EUR
 *    ({@link MOCK_PAYBIS_CAPTURE_METHODS_USDC_BASE}). This is the only real evidence behind the whole
 *    A7-b instant-only rule: there is no "1-2 business days" tag anywhere in a live Paybis payload.
 * 3. **The vendor minimum MOVES.** Across roughly four minutes the "at least N USDC per order" floor for
 *    card-family methods read `10.002` (9 USDC and 5 USDC quotes, ~15:52), then `10.003001` (the 10 USDC
 *    quotes, ~15:53-15:56), then back to `10.002` half an hour later (the 1 USDC quote, ~16:23). All
 *    three literal strings are kept on their own records below; nothing here averages or rounds them
 *    into one "the minimum is X" constant.
 * 4. **The service fee is near-FIXED below ~40 USDC, then roughly 4.4% above it.** The `credit-card`
 *    `fees.serviceFee.amount` reads EUR 1.86-1.88 at every one of 1, 5, 9, 10 and 11 USDC (1.86 / 1.87 /
 *    1.87 / 1.88 / 1.88 respectively), then EUR 3.83 / 4.02 / 7.84 / 9.76 at 100 / 105 / 205 / 255 USDC.
 *    All nine amounts are kept so this shape stays visible rather than collapsing to a single
 *    spot-checked ratio.
 *
 * ## Layout
 *
 * `src/mocks/data/paybisCapture/*.capture.json` hold the raw, redacted-then-synthesized wire bodies,
 * one file per endpoint shape, mirroring the established `*.dev.capture.json` convention
 * (`src/lib/onramp/fixtures/currencyPairsToBuy.dev.capture.json`, `PP-CORE-LIB-096`): a capture is
 * recorded data, not a hand-written literal, and stays in its own file so a diff against a future
 * re-capture is legible. This module is the typed, documented surface over them; it changes no runtime
 * behaviour and is not wired into `src/lib/services/index.ts` or any hook (S5 is fixtures, the mock
 * SERVICE that replays them is separate follow-up work).
 *
 * PP-MOCK: static, captured fixture data. Not read by any production code path today.
 */
import methodsEthBaseCapture from "./paybisCapture/paymentMethods.eur-eth-base.capture.json";
import methodsUsdcBaseCapture from "./paybisCapture/paymentMethods.eur-usdc-base.capture.json";
import methodsUsdcBaseRepeatCapture from "./paybisCapture/paymentMethods.eur-usdc-base.repeat.capture.json";
import quotesCapture from "./paybisCapture/quotes.capture.json";
import requestsCapture from "./paybisCapture/requests.capture.json";

/** One `{ amount, currencyCode }` money object, the wire's convention everywhere it prices something. */
export interface PaybisWireMoney {
  amount: string;
  currencyCode: string;
}

/**
 * One entry of `GET /v2/payment-methods/{from}/{to}`, exactly as Paybis sends it (before this app's own
 * {@link onRampPaymentMethodsResponseSchema} strips `id`/`name`/`fees`, POO-1603's note on
 * `wirePaymentMethodSchema`). Kept in full here because a captured wire body is the point: `fees` (the
 * rate/flat MODEL) is visible beside the quote's own priced `serviceFee` so a reader can compare the
 * two without guessing at the model Paybis actually uses.
 */
export interface PaybisWirePaymentMethodListEntry {
  paymentMethod: string;
  displayName: string;
  id: string;
  name: string;
  icon: string;
  minAmount: PaybisWireMoney;
  maxAmount: PaybisWireMoney;
  fees: { amount: string; isPercent: boolean };
  labels: string[];
}

/** One priced method inside a `POST /v2/quote` response. */
export interface PaybisWireQuotePaymentMethod {
  id: string;
  name: string;
  amountTo: PaybisWireMoney;
  amountFrom: PaybisWireMoney;
  amountToEquivalent: PaybisWireMoney;
  fees: {
    networkFee: PaybisWireMoney;
    serviceFee: PaybisWireMoney;
    totalFee: PaybisWireMoney;
  };
  feesInCrypto: {
    networkFee: PaybisWireMoney;
    serviceFee: PaybisWireMoney;
    totalFee: PaybisWireMoney;
  };
  expiration: string;
  expiresAt: string;
}

/** One method the quote could NOT price, in Paybis' own words. */
export interface PaybisWireQuoteMethodError {
  paymentMethod: string;
  error: { message: string; code: string };
}

/** The full `POST /v2/quote` response body, wire-shaped (synthetic `id`, see the module header). */
export interface PaybisWireQuoteResponse {
  id: string;
  currencyCodeTo: string;
  currencyCodeFrom: string;
  requestedAmount: PaybisWireMoney;
  requestedAmountType: string;
  paymentMethods: PaybisWireQuotePaymentMethod[];
  paymentMethodErrors?: PaybisWireQuoteMethodError[];
  exchangeRate: { from: string; to: string; rate: string };
  exchangeRateCryptoToFiat: { from: string; to: string; rate: string };
}

/** The `POST /v2/quote` request body this app actually sent for one captured record. */
export interface PaybisWireQuoteRequestBody {
  currencyCodeFrom: string;
  currencyCodeTo: string;
  amount: string;
  directionChange: string;
  isReceivedAmount: boolean;
  /** Absent = a LISTING quote (every method priced at once); present = pinned to one method. */
  paymentMethod?: string;
}

/** One captured quote round trip, request and response together, in original capture order. */
export interface PaybisCaptureQuoteRecord {
  /** Position in the original 19-record trace (0-indexed); stable across re-reads of the source. */
  sourceIndex: number;
  requestBody: PaybisWireQuoteRequestBody;
  responseBody: PaybisWireQuoteResponse;
}

/** The `POST /v3/request` body this app sends to mint a purchase (synthetic `quoteId`/wallet). */
export interface PaybisWireRequestBody {
  partnerUserId: string;
  userIp: string;
  quoteId: string;
  email: string;
  locale: string;
  cryptoWalletAddress: { address: string; currencyCode: string };
  paymentMethod: string;
  passwordless: boolean;
}

/** A refused `POST /v3/request` (HTTP 422): the quote could not be minted. */
export interface PaybisWireRequestErrorResponse {
  message: string;
  code: string;
  errors: Array<{ message: string; code: string; property_path: string }>;
}

/** An accepted `POST /v3/request` (HTTP 201): the id the widget opens with. */
export interface PaybisWireRequestSuccessResponse {
  requestId: string;
}

/**
 * The deterministic, valid-format (`0x` + 40 hex), self-evidently-mock wallet address every captured
 * `v3/request` body carries in place of the source's `[redacted:wallet-address]` placeholder. Same
 * seeded-hash approach as `src/mocks/data/pools.ts`'s `mockAddress`, seeded `"poo1598-paybis-capture-wallet"`.
 */
export const MOCK_PAYBIS_CAPTURE_WALLET = "0x06d61c2e80ffdefc172ae8789b228b181c7d93ba";

/**
 * `GET /v2/payment-methods/EUR/ETH-BASE`, captured 2026-08-17. The gas-first leg's method list
 * (POO-1573): 10 methods, real ids, real `minAmount`/`maxAmount`/`fees`/`labels`/`icon`. Note the ids
 * (`pool-party-credit-card`, `pool-party_bridgerpay_revolutpay`, …) differ from the invented
 * `poolparty-*` family in `src/mocks/data/onRampPaymentMethods.ts`; that divergence is itself the
 * finding POO-1598 exists to surface, not a mismatch to reconcile silently.
 */
export const MOCK_PAYBIS_CAPTURE_METHODS_ETH_BASE: readonly PaybisWirePaymentMethodListEntry[] =
  methodsEthBaseCapture.data;

/**
 * `GET /v2/payment-methods/EUR/USDC-BASE`, captured 2026-08-17, ~90 seconds before
 * {@link MOCK_PAYBIS_CAPTURE_METHODS_ETH_BASE}. Same 10 methods, same ids; `pool-party-manual-bank-transfer`
 * (SEPA) and `pool-party_bridgerpay_paypal`'s `maxAmount` differ from the ETH-BASE list (SEPA:
 * EUR 500,000 here vs 1,000,000 there), which is real evidence that the method list is priced PER PAIR,
 * not just per fiat.
 */
export const MOCK_PAYBIS_CAPTURE_METHODS_USDC_BASE: readonly PaybisWirePaymentMethodListEntry[] =
  methodsUsdcBaseCapture.data;

/**
 * A second `GET /v2/payment-methods/EUR/USDC-BASE` capture, ~4 minutes after
 * {@link MOCK_PAYBIS_CAPTURE_METHODS_USDC_BASE}, immediately before the capture's failed (422) mint
 * attempt. Every method's `maxAmount` drifted slightly (e.g. `pool-party-credit-card`: EUR 17,259.14 to
 * 17,261.14); `minAmount` did not move in this window. Real evidence that the list's ceilings are
 * price-derived and live, not a static catalog re-served from cache.
 */
export const MOCK_PAYBIS_CAPTURE_METHODS_USDC_BASE_REPEAT: readonly PaybisWirePaymentMethodListEntry[] =
  methodsUsdcBaseRepeatCapture.data;

/**
 * All 13 captured `POST /v2/quote` round trips, in original capture order. Covers every amount the
 * capture exercised (1, 5, 9, 10, 11, 100, 105, 205, 255 USDC), including the 10 USDC and 11 USDC
 * amounts requested more than once (a listing quote and one or two method-pinned quotes each), because
 * the repeats are exactly where the controlled priced-and-refused pair lives (see the module header).
 */
export const MOCK_PAYBIS_CAPTURE_QUOTES: readonly PaybisCaptureQuoteRecord[] = quotesCapture;

/**
 * A named quote at a fixed, known-good position in {@link MOCK_PAYBIS_CAPTURE_QUOTES}. A runtime check
 * rather than a non-null assertion: `noUncheckedIndexedAccess` makes bracket access `| undefined`
 * regardless of how confident the caller is, and this throws with a clear reason instead of silently
 * exporting `undefined` under a named constant if the capture array is ever edited to a different
 * length. Every call site below passes a literal index into the FIXED, already-verified capture.
 */
function requireCaptureQuote(index: number): PaybisCaptureQuoteRecord {
  const record = MOCK_PAYBIS_CAPTURE_QUOTES[index];
  if (!record) {
    throw new Error(`paybisCapture: expected a captured quote record at index ${index}`);
  }
  return record;
}

/** 100 USDC, every method listed. Corrupted-rate record (see header). */
export const MOCK_PAYBIS_CAPTURE_QUOTE_100USDC = requireCaptureQuote(0);
/** 9 USDC, every method listed; every card-family method already below the 10.002 USDC floor. Corrupted-rate record. */
export const MOCK_PAYBIS_CAPTURE_QUOTE_9USDC = requireCaptureQuote(1);
/** 5 USDC, every method listed; ALL 10 methods priced AND refused (the lowest amount in the capture). Corrupted-rate record. */
export const MOCK_PAYBIS_CAPTURE_QUOTE_5USDC = requireCaptureQuote(2);
/** 105 USDC, every method listed; only SEPA refused (below its ~231.45 USDC floor). */
export const MOCK_PAYBIS_CAPTURE_QUOTE_105USDC = requireCaptureQuote(3);
/** 205 USDC, every method listed; only SEPA refused. */
export const MOCK_PAYBIS_CAPTURE_QUOTE_205USDC = requireCaptureQuote(4);
/** 255 USDC, every method listed; no refusals at all (above every method's floor). Corrupted-rate record. */
export const MOCK_PAYBIS_CAPTURE_QUOTE_255USDC = requireCaptureQuote(5);
/** 10 USDC, every method listed; 9 of 10 refused (all but the lower-floor `paysafe_apm`). */
export const MOCK_PAYBIS_CAPTURE_QUOTE_10USDC_ALL = requireCaptureQuote(6);
/** 10 USDC, pinned to Google Pay: priced AND refused (min 10.002 USDC), the same shape as the card twin below. */
export const MOCK_PAYBIS_CAPTURE_QUOTE_10USDC_GOOGLE_PAY = requireCaptureQuote(7);
/** 10 USDC, pinned to card, first attempt: priced AND refused (min 10.003001 USDC). */
export const MOCK_PAYBIS_CAPTURE_QUOTE_10USDC_CARD_A = requireCaptureQuote(8);
/**
 * 10 USDC, pinned to card, second attempt: priced AND refused (min 10.003001 USDC). POO-1666's exact
 * root cause and the quote {@link MOCK_PAYBIS_CAPTURE_REQUEST_422} replays.
 */
export const MOCK_PAYBIS_CAPTURE_QUOTE_10USDC_CARD_B = requireCaptureQuote(9);
/** 1 USDC, pinned to card: priced AND refused (min 10.002 USDC, back down from 10.003001 half an hour later). */
export const MOCK_PAYBIS_CAPTURE_QUOTE_1USDC_CARD = requireCaptureQuote(10);
/** 11 USDC, pinned to card, first attempt: priced, NO `paymentMethodErrors`, the controlled twin of the 10 USDC pair. */
export const MOCK_PAYBIS_CAPTURE_QUOTE_11USDC_CARD_A = requireCaptureQuote(11);
/**
 * 11 USDC, pinned to card, second attempt: priced, NO `paymentMethodErrors`. The exact quote
 * {@link MOCK_PAYBIS_CAPTURE_REQUEST_201} mints.
 */
export const MOCK_PAYBIS_CAPTURE_QUOTE_11USDC_CARD_B = requireCaptureQuote(12);

/**
 * The refused `POST /v3/request` (HTTP 422): submitted against
 * {@link MOCK_PAYBIS_CAPTURE_QUOTE_10USDC_CARD_B}'s quote id, refused with "There are no available
 * payment/payout methods in Quote" because the priced method's own minimum was not met. This is what a
 * quote carrying BOTH a priced method and that same method's own refusal actually does when minted.
 */
export const MOCK_PAYBIS_CAPTURE_REQUEST_422: {
  status: number;
  requestBody: PaybisWireRequestBody;
  responseBody: PaybisWireRequestErrorResponse;
} = requestsCapture["422"];

/**
 * The accepted `POST /v3/request` (HTTP 201): submitted against
 * {@link MOCK_PAYBIS_CAPTURE_QUOTE_11USDC_CARD_B}'s quote id, minted a `requestId`. The 11 USDC twin of
 * the refused 10 USDC pair above, same payment method, one order of magnitude apart in fiat and nothing
 * else.
 */
export const MOCK_PAYBIS_CAPTURE_REQUEST_201: {
  status: number;
  requestBody: PaybisWireRequestBody;
  responseBody: PaybisWireRequestSuccessResponse;
} = requestsCapture["201"];

/** Find a captured quote record by its (synthetic) quote id. Pure lookup, no I/O, no mutation. */
export function findPaybisCaptureQuoteById(quoteId: string): PaybisCaptureQuoteRecord | undefined {
  return MOCK_PAYBIS_CAPTURE_QUOTES.find((record) => record.responseBody.id === quoteId);
}
