/**
 * @id PP-TOOLS-LIB-003
 * @name Foundry project materialisation
 * @implements-rules-version v1
 * @analytics-events none
 *
 * Turns a verified source set into a Foundry project hookrisk can scan.
 *
 * A standard-json verification is self-contained: it carries every file solc saw, at the paths solc
 * saw them at, plus the remappings that made the imports resolve. So the job is to write it back out
 * unchanged and describe it to foundry, not to reconstruct a dependency tree. `forge build` then
 * reproduces the original compilation, and hookrisk reads the artifacts.
 *
 * The one thing done defensively is path handling. Those paths were chosen by whoever verified the
 * contract, and this process writes them to disk; {@link sanitizeSourcePath} is why a source named
 * `../../../etc/cron.d/x` lands inside the job directory like everything else.
 */
import "server-only";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { ContractSource, SourceFile } from "./explorer";

/** A file to write, relative to the job directory. */
export interface PlannedFile {
  path: string;
  content: string;
}

/** The materialisation plan: what to write, and what to then tell hookrisk to scan. */
export interface ProjectPlan {
  files: PlannedFile[];
  /** Entry path AFTER sanitisation, relative to the project root. */
  entryFile: string;
  /** First segment of {@link entryFile}: what `foundry.toml` sets `src` to. */
  srcDir: string;
}

/**
 * A repo-relative, traversal-free version of an explorer-supplied path, or null when nothing
 * usable survives.
 *
 * Segments are filtered rather than the string being rejected: a path like `src/../lib/A.sol` is a
 * legitimate (if ugly) source key, and dropping the traversal keeps the file while making the
 * destination unambiguous.
 */
export function sanitizeSourcePath(raw: string): string | null {
  const segments = raw
    .replace(/\\/g, "/")
    .split("/")
    .map((segment) => segment.trim())
    .filter((segment) => segment.length > 0 && segment !== "." && segment !== "..");
  if (segments.length === 0) return null;
  return segments.join("/");
}

/** `foundry.toml` reproducing the original compilation, with `src` pointed at `srcDir`. */
export function buildFoundryToml(source: ContractSource, srcDir: string): string {
  const lines = [
    "# Generated by PP-TOOLS-LIB-003 for a single hookrisk scan. Not a checked-in project.",
    "[profile.default]",
    `src = "${srcDir}"`,
    'out = "out"',
    'libs = ["lib"]',
    `optimizer = ${source.optimizer.enabled}`,
    `optimizer_runs = ${source.optimizer.runs}`,
    // hookrisk reads the AST out of the artifacts, so it has to be emitted.
    'extra_output = ["storageLayout"]',
    "ast = true",
  ];
  // Pin only what the explorer gave us a usable value for. An unpinned solc lets foundry resolve a
  // version that exists; a pinned nightly fails the download and takes the whole scan with it.
  if (source.solcVersion) lines.push(`solc = "${source.solcVersion}"`);
  if (source.evmVersion) lines.push(`evm_version = "${source.evmVersion}"`);
  return `${lines.join("\n")}\n`;
}

/** The `File.sol:Contract` string the hookrisk CLI takes as its scan target. */
export function hookriskTarget(source: Pick<ContractSource, "entryFile" | "contractName">): string {
  return `${source.entryFile}:${source.contractName}`;
}

/** Place a file: verbatim where it has a directory, under `src/` when it is a bare filename. */
function placeFile(file: SourceFile): PlannedFile | null {
  const safe = sanitizeSourcePath(file.path);
  if (!safe) return null;
  return { path: safe.includes("/") ? safe : `src/${safe}`, content: file.content };
}

/** Everything to write for one scan, plus the target and `src` directory that follow from it. */
export function planProject(source: ContractSource): ProjectPlan {
  const placed = source.files
    .map((file) => ({ original: file.path, planned: placeFile(file) }))
    .filter((entry): entry is { original: string; planned: PlannedFile } => entry.planned !== null);

  const entry =
    placed.find((item) => item.original === source.entryFile)?.planned.path ??
    placed[placed.length - 1]?.planned.path ??
    `src/${source.contractName}.sol`;
  const srcDir = entry.split("/")[0] ?? "src";

  const files: PlannedFile[] = [
    { path: "foundry.toml", content: buildFoundryToml(source, srcDir) },
    ...placed.map((item) => item.planned),
  ];
  if (source.remappings.length > 0) {
    files.push({ path: "remappings.txt", content: `${source.remappings.join("\n")}\n` });
  }

  return { files, entryFile: entry, srcDir };
}

/** Write a plan into `dir`, creating parent directories as needed. */
export async function writeProject(dir: string, plan: ProjectPlan): Promise<void> {
  for (const file of plan.files) {
    const absolute = join(dir, file.path);
    await mkdir(dirname(absolute), { recursive: true });
    await writeFile(absolute, file.content, "utf8");
  }
}
