/**
 * @id PP-TOOLS-CMP-002
 * @name MarkdownReport
 * @implements-rules-version v1
 * @analytics-events none (presentational; PP-TOOLS-CMP-001 owns the funnel)
 *
 * Renders `HOOK_RISK.md` on the app's dark surface.
 *
 * The report is generated by our own tool, so the threat model here is thin. It is still rendered
 * with raw HTML OFF, which is react-markdown's default and is left alone deliberately: the report
 * quotes contract source, revert strings and detector output, all of which are attacker-authored
 * text that happens to travel through a trusted generator. Passing `rehype-raw` to make one table
 * render nicer would turn that into stored XSS, so it is not installed.
 *
 * Styling is explicit per element rather than a prose plugin: the report is the only Markdown this
 * app renders, one component is cheaper than a typography dependency, and the score tables need
 * their own horizontal-scroll container at phone width anyway.
 */
"use client";

import type { ComponentPropsWithoutRef } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { cn } from "@/lib/utils/cn";

type ElementProps<T extends keyof React.JSX.IntrinsicElements> = ComponentPropsWithoutRef<T>;

export interface MarkdownReportProps {
  /** Raw Markdown. Rendered as-is; no HTML is interpreted. */
  markdown: string;
  className?: string;
}

/** Render one hookrisk report. */
export function MarkdownReport({ markdown, className }: MarkdownReportProps) {
  return (
    <div className={cn("text-foreground text-sm leading-relaxed", className)}>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          h1: ({ className: c, ...props }: ElementProps<"h1">) => (
            <h1 className={cn("mt-8 mb-3 font-semibold text-2xl first:mt-0", c)} {...props} />
          ),
          h2: ({ className: c, ...props }: ElementProps<"h2">) => (
            <h2
              className={cn(
                "mt-8 mb-3 border-border border-b pb-2 font-semibold text-xl first:mt-0",
                c,
              )}
              {...props}
            />
          ),
          h3: ({ className: c, ...props }: ElementProps<"h3">) => (
            <h3 className={cn("mt-6 mb-2 font-semibold text-base", c)} {...props} />
          ),
          h4: ({ className: c, ...props }: ElementProps<"h4">) => (
            <h4 className={cn("mt-4 mb-2 font-semibold text-sm", c)} {...props} />
          ),
          p: ({ className: c, ...props }: ElementProps<"p">) => (
            <p className={cn("my-3 text-muted-foreground", c)} {...props} />
          ),
          ul: ({ className: c, ...props }: ElementProps<"ul">) => (
            <ul
              className={cn("my-3 list-disc space-y-1 pl-6 text-muted-foreground", c)}
              {...props}
            />
          ),
          ol: ({ className: c, ...props }: ElementProps<"ol">) => (
            <ol
              className={cn("my-3 list-decimal space-y-1 pl-6 text-muted-foreground", c)}
              {...props}
            />
          ),
          a: ({ className: c, ...props }: ElementProps<"a">) => (
            <a
              className={cn("text-primary underline underline-offset-2 hover:opacity-80", c)}
              target="_blank"
              rel="noreferrer noopener"
              {...props}
            />
          ),
          blockquote: ({ className: c, ...props }: ElementProps<"blockquote">) => (
            <blockquote
              className={cn("my-4 border-border border-l-2 pl-4 text-muted-foreground", c)}
              {...props}
            />
          ),
          hr: ({ className: c, ...props }: ElementProps<"hr">) => (
            <hr className={cn("my-6 border-border", c)} {...props} />
          ),
          code: ({ className: c, ...props }: ElementProps<"code">) => (
            <code
              className={cn(
                "rounded bg-surface-raised px-1.5 py-0.5 font-mono text-[0.85em] text-foreground",
                c,
              )}
              {...props}
            />
          ),
          // A fenced block: its own scroll container, so a long solidity line never widens the page.
          pre: ({ className: c, ...props }: ElementProps<"pre">) => (
            <pre
              className={cn(
                "my-4 overflow-x-auto rounded-md border border-border bg-surface-raised p-4 font-mono text-xs",
                c,
              )}
              {...props}
            />
          ),
          // The score and findings tables are wide by nature. Same treatment.
          table: ({ className: c, ...props }: ElementProps<"table">) => (
            <div className="my-4 w-full overflow-x-auto rounded-md border border-border">
              <table className={cn("w-full border-collapse text-left text-xs", c)} {...props} />
            </div>
          ),
          th: ({ className: c, ...props }: ElementProps<"th">) => (
            <th
              className={cn(
                "border-border border-b bg-surface-raised px-3 py-2 font-semibold text-foreground",
                c,
              )}
              {...props}
            />
          ),
          td: ({ className: c, ...props }: ElementProps<"td">) => (
            <td
              className={cn("border-border border-b px-3 py-2 align-top text-muted-foreground", c)}
              {...props}
            />
          ),
          strong: ({ className: c, ...props }: ElementProps<"strong">) => (
            <strong className={cn("font-semibold text-foreground", c)} {...props} />
          ),
        }}
      >
        {markdown}
      </ReactMarkdown>
    </div>
  );
}
