"""Canonical Uniswap v4 hook interface constants.

DO NOT EDIT. Generated by `scripts/gen_hooks_spec.py` from a pinned checkout of
Uniswap/v4-core. Regenerate with `make spec`; CI fails if this file drifts from
what the pinned source produces.

Provenance
----------
Uniswap/v4-core @ 46c6834698c48bc4a463a86d8420f4eb1d7f3b75
  src/libraries/Hooks.sol       -> FLAG_BITS
  src/interfaces/IHooks.sol     -> CALLBACK_SIGNATURES
  src/types/{PoolKey,PoolOperation,BalanceDelta,BeforeSwapDelta,Currency}.sol
Selector digests computed by `cast sig` (Foundry).
"""

from __future__ import annotations

V4_CORE_COMMIT = "46c6834698c48bc4a463a86d8420f4eb1d7f3b75"

#: Bit position of each permission flag inside the low 14 bits of a hook address.
FLAG_BITS: dict[str, int] = {
    "BEFORE_INITIALIZE_FLAG": 13,
    "AFTER_INITIALIZE_FLAG": 12,
    "BEFORE_ADD_LIQUIDITY_FLAG": 11,
    "AFTER_ADD_LIQUIDITY_FLAG": 10,
    "BEFORE_REMOVE_LIQUIDITY_FLAG": 9,
    "AFTER_REMOVE_LIQUIDITY_FLAG": 8,
    "BEFORE_SWAP_FLAG": 7,
    "AFTER_SWAP_FLAG": 6,
    "BEFORE_DONATE_FLAG": 5,
    "AFTER_DONATE_FLAG": 4,
    "BEFORE_SWAP_RETURNS_DELTA_FLAG": 3,
    "AFTER_SWAP_RETURNS_DELTA_FLAG": 2,
    "AFTER_ADD_LIQUIDITY_RETURNS_DELTA_FLAG": 1,
    "AFTER_REMOVE_LIQUIDITY_RETURNS_DELTA_FLAG": 0,
}

#: Canonical ABI signature of every IHooks callback.
CALLBACK_SIGNATURES: dict[str, str] = {
    "beforeInitialize": "beforeInitialize(address,(address,address,uint24,int24,address),uint160)",
    "afterInitialize": "afterInitialize(address,(address,address,uint24,int24,address),uint160,int24)",
    "beforeAddLiquidity": "beforeAddLiquidity(address,(address,address,uint24,int24,address),(int24,int24,int256,bytes32),bytes)",
    "afterAddLiquidity": "afterAddLiquidity(address,(address,address,uint24,int24,address),(int24,int24,int256,bytes32),int256,int256,bytes)",
    "beforeRemoveLiquidity": "beforeRemoveLiquidity(address,(address,address,uint24,int24,address),(int24,int24,int256,bytes32),bytes)",
    "afterRemoveLiquidity": "afterRemoveLiquidity(address,(address,address,uint24,int24,address),(int24,int24,int256,bytes32),int256,int256,bytes)",
    "beforeSwap": "beforeSwap(address,(address,address,uint24,int24,address),(bool,int256,uint160),bytes)",
    "afterSwap": "afterSwap(address,(address,address,uint24,int24,address),(bool,int256,uint160),int256,bytes)",
    "beforeDonate": "beforeDonate(address,(address,address,uint24,int24,address),uint256,uint256,bytes)",
    "afterDonate": "afterDonate(address,(address,address,uint24,int24,address),uint256,uint256,bytes)",
}

#: 4-byte selector of every IHooks callback.
CALLBACK_SELECTORS: dict[str, str] = {
    "beforeInitialize": "0xdc98354e",
    "afterInitialize": "0x6fe7e6eb",
    "beforeAddLiquidity": "0x259982e5",
    "afterAddLiquidity": "0x9f063efc",
    "beforeRemoveLiquidity": "0x21d0ee70",
    "afterRemoveLiquidity": "0x6c2bbe7e",
    "beforeSwap": "0x575e24b4",
    "afterSwap": "0xb47b2fb1",
    "beforeDonate": "0xb6a8b0fa",
    "afterDonate": "0xe1b4af69",
}

#: Solidity user-defined value types and the ABI type each erases to.
#:
#: Needed because Slither renders these inconsistently in
#: `Function.solidity_signature`: in one and the same `PoolKey` tuple it emits
#: `address` for `currency0` and `Currency` for `currency1`. Comparing a
#: Slither signature to a canonical ABI signature therefore requires normalising
#: these names away first — see `normalize_signature` in utils/hook_analysis.py.
VALUE_TYPE_ALIASES: dict[str, str] = {
    "BalanceDelta": "int256",
    "BeforeSwapDelta": "int256",
    "Currency": "address",
    "PoolId": "bytes32",
    "Slot0": "bytes32",
}

#: The permission flag each callback is gated by. A hook whose address lacks the
#: flag is never invoked for that callback, however complete its implementation.
CALLBACK_TO_FLAG: dict[str, str] = {
    "beforeInitialize": "BEFORE_INITIALIZE_FLAG",
    "afterInitialize": "AFTER_INITIALIZE_FLAG",
    "beforeAddLiquidity": "BEFORE_ADD_LIQUIDITY_FLAG",
    "afterAddLiquidity": "AFTER_ADD_LIQUIDITY_FLAG",
    "beforeRemoveLiquidity": "BEFORE_REMOVE_LIQUIDITY_FLAG",
    "afterRemoveLiquidity": "AFTER_REMOVE_LIQUIDITY_FLAG",
    "beforeSwap": "BEFORE_SWAP_FLAG",
    "afterSwap": "AFTER_SWAP_FLAG",
    "beforeDonate": "BEFORE_DONATE_FLAG",
    "afterDonate": "AFTER_DONATE_FLAG",
}

#: Flags that let a hook return a delta, i.e. take a cut of the swap or of a
#: liquidity operation. These are the "custom accounting" permissions: their
#: presence changes which invariants the differential harness may assert.
RETURNS_DELTA_FLAGS: tuple[str, ...] = (
    "BEFORE_SWAP_RETURNS_DELTA_FLAG",
    "AFTER_SWAP_RETURNS_DELTA_FLAG",
    "AFTER_ADD_LIQUIDITY_RETURNS_DELTA_FLAG",
    "AFTER_REMOVE_LIQUIDITY_RETURNS_DELTA_FLAG",
)

#: A returns-delta flag is only honoured when its parent action flag is also set;
#: `Hooks.isValidHookAddress` rejects the mismatched combinations outright.
RETURNS_DELTA_PARENT: dict[str, str] = {
    "BEFORE_SWAP_RETURNS_DELTA_FLAG": "BEFORE_SWAP_FLAG",
    "AFTER_SWAP_RETURNS_DELTA_FLAG": "AFTER_SWAP_FLAG",
    "AFTER_ADD_LIQUIDITY_RETURNS_DELTA_FLAG": "AFTER_ADD_LIQUIDITY_FLAG",
    "AFTER_REMOVE_LIQUIDITY_RETURNS_DELTA_FLAG": "AFTER_REMOVE_LIQUIDITY_FLAG",
}

#: Mask covering every permission bit; `Hooks.ALL_HOOK_MASK` in v4-core.
ALL_HOOK_MASK: int = (1 << 14) - 1

#: Sentinel `PoolKey.fee` marking a dynamic-fee pool (`LPFeeLibrary`).
DYNAMIC_FEE_FLAG: int = 0x800000

#: Highest LP fee v4 accepts, in hundredths of a bip (100%).
MAX_LP_FEE: int = 1_000_000


def flags_from_address(address: str) -> dict[str, bool]:
    """Decode a deployed hook address into its permission set.

    v4 derives permissions from the low 14 bits of the address itself, so this
    is the ground truth for a deployed hook regardless of what its source says.
    """
    value = int(address, 16) & ALL_HOOK_MASK
    return {name: bool(value & (1 << bit)) for name, bit in FLAG_BITS.items()}
